added success step and change the workflow trigger

diff --git a/.github/workflows/01-building-blocks.yaml b/.github/workflows/01-building-blocks.yaml
--- a/.github/workflows/01-building-blocks.yaml
+++ b/.github/workflows/01-building-blocks.yaml
@@ -1,6 +1,6 @@
 name: 01- Building Blocks
 on: 
-    - push
+    # - push
     - workflow_dispatch
 jobs:
     echo-hello:
@@ -11,9 +11,13 @@ jobs:
     echo-goodbye: 
         runs-on: ubuntu-latest
         steps: 
-          - name: Failed step
+        #   - name: Failed step
+        #     run: |
+        #       echo "I will fail"
+        #       exit 1
+          - name: Success step
             run: |
-              echo "I will fail"
+              echo "I will Success"
               exit 0
           - name: Say goodbye
             run: echo "Goodbye!"
